### ISSUE TITLE
RS232 Converter Supply 3.3V

### ISSUE THREAD

**Issue by wavoigt** [GyroGearl00se/ESPHome-Froeling-Lambdatronic_3200#19]
Remember, you should supply the RS232 converter with 3.3V from D1 mini, if you supply it with VCC 5V the logic high level of the converter is 5V, and this may damage the input of the ESP. 
If you you want to supply the converter with 5V you should at least put a 1k Resistor in the rx line of the ESP.

**Comment by GyroGearl00se** [comment]
https://github.com/GyroGearl00se/ESPHome-Froeling-Lambdatronic_3200/commit/fed8f7fa491cc7659f87733882d1a7760310ac45

Thx - forgot about changing that :)
Updated docs/pictures accordingly.
