### ISSUE TITLE
Error when updating esphome

### ISSUE THREAD

**Issue by wavoigt** [GyroGearl00se/ESPHome-Froeling-Lambdatronic_3200#35]
Hi,
I updated froeling.yaml with:
<pre>ota:
  - platform: esphome
    password: ""
</pre>
Now when updating esphome i get the following error message:
![Zwischenablage_07-04-2024_01](https://github.com/GyroGearl00se/ESPHome-Froeling-Lambdatronic_3200/assets/24320737/ddc29656-8d6a-4205-8cdb-dead61ffbe89)
my Froeling.yaml is:
[froeling.yaml.txt](https://github.com/user-attachments/files/16097973/froeling.yaml.txt)
What can i do?

**Comment by GyroGearl00se** [comment]
This change is related to https://esphome.io/changelog/2024.6.0.html#ota-platforms

According to your screenshot you're already running the latest version 2024.6.6

Maybe you could try cleaning up build files ?
![image](https://github.com/GyroGearl00se/ESPHome-Froeling-Lambdatronic_3200/assets/94406798/0e248abb-f2a2-4e41-a8d7-989b4009c21b)

@Matze5593: Any ideas ?

**Comment by Matze5593** [comment]
![image](https://github.com/GyroGearl00se/ESPHome-Froeling-Lambdatronic_3200/assets/55891473/82126a1d-8019-4cab-b460-88173962601b)
![image](https://github.com/GyroGearl00se/ESPHome-Froeling-Lambdatronic_3200/assets/55891473/5ae0b7c8-e45f-40be-92f2-542481139bd3)


Hmmm.

I have already implemented this OTA Platform esphome, myself. but i have no problems. But my yaml is a little different.

**Comment by wavoigt** [comment]
Vielen Dank, das Update hat jetzt funktioniert, "Clean Build files" war das Zauberwort.
Hätte ich auch selber drauf kommen können...
Jetzt hab ich in der ESP Konsole -> "Visit" noch 1 Warnung und 1 Fehlermeldung:

<pre>17:34:49	[D]	[sensor:094]	
'froeling Aktuelle Ansteuerung der Kollektor - Boiler Pumpe': Sending state 0.00000 h with 0 decimals of accuracy
17:34:49	[W]	[component:237]	
Component modbus_controller took a long time for an operation (52 ms).
17:34:49	[W]	[component:238]	
Components should block for at most 30 ms.
17:34:49	[D]	[text_sensor:064]	
'froeling Anlagenzustand': Sending state 'Automatik'
17:34:49	[D]	[text_sensor:064]	
'froeling Kesselzustand': Sending state 'Betriebsbereit'
17:34:49	[D]	[modbus:125]	
**Modbus error function code: 0x84 exception: 2
17:34:49	[E]	[modbus_controller:088]	
Modbus error function code: 0x4 exception: 2 
17:34:49	[E]	[modbus_controller:097]	
Modbus error - last command: function code=0x4  register address = 0x7F6B  registers count=1 payload size=0**</pre>

Aber sonst scheint alles zu funktionieren.

**Comment by Matze5593** [comment]
![Screenshot_20240704_174814_Chrome.jpg](https://github.com/GyroGearl00se/ESPHome-Froeling-Lambdatronic_3200/assets/55891473/db073fbe-9141-47fe-ba2f-f1b989157bcc)

Das kommt aus der Solarthermie yaml
Das ist der Tippfehler der "3". Es hat bei die Dateien nicht neu geladen. In der froeling yaml gibt es das refresh 1d.
Stell das mal auf 1h und mach clear build. Anschließend noch mal installieren. Dann sollte es sich die noch mal neu ziehen. Oder du wartest bist morgen und installierst dann noch mal. Hätte den selben Effekt

**Comment by wavoigt** [comment]
Danke. der Tip mit dem Refresh hat geholfen.
Alles TOP :-)
