### ISSUE TITLE
 Hint about doubled froeling entry in the entities needed

### ISSUE THREAD

**Issue by ranseyer** [GyroGearl00se/ESPHome-Froeling-Lambdatronic_3200#43]
Hi,

my installation of this nice Software needed ~6 months, ...

After i build the hardware i found out that the froeling firmware was on version behind, that modbus 2014 would be possible.

Today i got the new firmware and i see data. Because of some trouble i have deletet the ESPHome device and created it again.

But the sensors have one froeling too much in the name and i was not able to find the reason.
Example:
sensor.froeling_froeling_abgastemperatur

Does somebody have a hint for me ?

> esphome:
>   name: froeling
>   friendly_name: froeling
> 
> esp32:
>   board: lolin_s2_mini
>   framework:
>     type: arduino
> 
> # Enable logging
> logger:
> #  baud_rate: 0
> #  level: INFO
> 
> # Enable Home Assistant API
> api:
>   encryption:
>     key: "1+Lsxxx2ZH1ic="
> 
> ota:
>   - platform: esphome
>     password: "66f8xxa28e9"
> 
> wifi:
>   ssid: !secret wifi_ssid
>   password: !secret wifi_password
>   ap:
>     ssid: "Froeling Fallback Hotspot"
>     password: "LExxxKaaz"
>   manual_ip:
>     static_ip: 192.168.1.96
>     gateway: 192.168.1.1
>     subnet: 255.255.255.0
> 
> 
> captive_portal:
>   # Enable fallback hotspot (captive portal) in case wifi connection fails
> 
> web_server:
>   port: 80
> 
> 
> substitutions:
>   name: froeling
>   modbus_controller_id: froeling
> 
> uart:
>   - id: uartfroeling
>     tx_pin: 16
>     rx_pin: 17
>     baud_rate: 57600
>     data_bits: 8
>     stop_bits: 1
>     parity: NONE
> 
> modbus:
>   id: modbus1
>   uart_id: uartfroeling
> 
> modbus_controller:
>   - id: froeling
>     address: 2
>     modbus_id: modbus1
>     setup_priority: -10
>     update_interval: "60s"
>     command_throttle: "50ms"
> 
> switch:
>   - platform: restart
>     name: "Restart ESP"
> 
> 
> packages:
>   remote_package:
>     url: https://github.com/GyroGearl00se/ESPHome-Froeling-Lambdatronic_3200
>     ref: main
>     files: [
>       austragung.yaml,
>       boiler_01.yaml,
>       heizkreis01.yaml,
>       kessel.yaml,
>       puffer_01.yaml,
>       zirkulationspumpe.yaml,
>       ]
> 
>     refresh: 1d
> 
> sensor:
>   - platform: modbus_controller
>     modbus_controller_id: ${modbus_controller_id}
>     name: "${name} Aussentemperatur"
>     id: ${name}_Aussentemperatur
>     register_type: read
>     address: 1000
>     unit_of_measurement: "°C"
>     device_class: "temperature"
>     state_class: "measurement"
>     value_type: S_WORD
>     filters:
>       - multiply: 0.5
> 
....

**Comment by GyroGearl00se** [comment]
Hi @ranseyer,
I'm not entirely sure, but it could be that even if you deleted the esphome device, that there might have been still some "left overs" in Home Assistant.

I'd suggest to delete the device, restart Home Assistant, go "Settings > Devices & Integrations > Entities" and check if you can find any remaining entity related to your esphome froeling device. If still exists - delete it.

If not - I assume that maybe you're facing the same issue as described here: https://github.com/esphome/feature-requests/issues/2476

Others in that issue shared following workaround:

esphome:
  friendly_name: " "

No idea if this will work for you and if it comes with anydownsides.

**Comment by ranseyer** [comment]
Thank you, after trying=deleting a lot (including froeling from the fritzbox an ping intergration) and some restarts i had no success... (froling from dns was als renames to froeling-esp32) ...

The only an working solution was to change the esphome definition yaml file as:

esphome:
  name: froeling
  friendly_name: ""
...

**Comment by ranseyer** [comment]
Thanks !
